language: java
jdk: openjdk8
script: mvn -X -Dmaven.test.skip=true install 

# Add init for UI Tests -> Must be checked (doesn not work anymore on travis...)
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start
